services:
  - type: web
    name: localloop-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
